mod exercises;

fn main() {
    // exercises::guessing_game::start();
    // exercises::variables::start();
    // exercises::functions::start();
    // exercises::branches::start();
    // exercises::ch3practise::start();
    // exercises::ownership::start();
    // exercises::refs_and_borrowing::start();
    // exercises::slices::start();
    // exercises::structs::start();
    // exercises::rectangles::start();
    // exercises::enums::start();
    // exercises::matches::start();
    // exercises::iflet::start();
    // exercises::vectors::start();
    // exercises::strings::start();
    // exercises::hash_maps::start();
    // exercises::ch8practise::start();
    // exercises::errors::start();
    // exercises::generics::start();
    // exercises::traits::start();
    // exercises::lifetimes::start();
    // exercises::testing::start();
    // exercises::closures::start();
    // exercises::iterators::start();
    // exercises::smart_pointers::start();
    // exercises::threads::start();
    // exercises::message_parsing::start();
    // exercises::shared_state_concurrency::start();
    // exercises::extensible_concurrency::start();
    // exercises::traits_for_common_behaviour::start();
    // exercises::state_pattern_traditional_oop::start();
    // exercises::state_pattern_rusty::start();
    // exercises::patterns::start();
    // exercises::unsafe_rust::start();
    // exercises::advanced_traits::start();
    // exercises::advanced_types::start();
    // exercises::advanced_functions_closures::start();
    exercises::macros::start();
}
